src/AppBundle/Entity/Article.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Article
 *
 * @ORM\Table(name="article")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ArticleRepository")
 */
class Article
{
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->insertedAt = new \Datetime;
        $this->votes = new ArrayCollection();
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="link", type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="inserted_at", type="datetime")
     */
    private $insertedAt;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\ArticleVote", mappedBy="article")
     */
    private $votes;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\ArticleCategory", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\ArticleStatus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;


    /**
     * Get id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Article
     */
    public function setTitle(string $title): Article
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Article
     */
    public function setDescription(string $description): Article
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set link
     *
     * @param string $link
     *
     * @return Article
     */
    public function setLink(string $link): Article
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Set insertedAt
     *
     * @param \DateTime $insertedAt
     *
     * @return Article
     */
    public function setInsertedAt(\DateTime $insertedAt): Article
    {
        $this->insertedAt = $insertedAt;

        return $this;
    }

    /**
     * Get insertedAt
     *
     * @return \DateTime
     */
    public function getInsertedAt(): \DateTime
    {
        return $this->insertedAt;
    }

    /**
     * Set User
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Article
     */
    public function setUser(User $user): Article
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Get votes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Get accepted votes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAcceptedVotes()
    {
        $votes = new ArrayCollection();
        foreach ($this->votes as $vote) {
            if ($vote->isAccepted()) {
                $votes[] = $vote;
            }
        }

        return $votes;
    }

    /**
     * Get refused votes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRefusedVotes()
    {
        $votes = new ArrayCollection();
        foreach ($this->votes as $vote) {
            if (!$vote->isAccepted()) {
                $votes[] = $vote;
            }
        }

        return $votes;
    }

    /**
     * Set category
     *
     * @param \AppBundle\Entity\ArticleCategory $category
     *
     * @return Article
     */
    public function setCategory(ArticleCategory $category): Article
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \AppBundle\Entity\ArticleCategory
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set status
     *
     * @param \AppBundle\Entity\ArticleStatus $status
     *
     * @return Article
     */
    public function setStatus(ArticleStatus $status): Article
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return \AppBundle\Entity\ArticleStatus
     */
    public function getStatus()
    {
        return $this->status;
    }
}

src/AppBundle/Form/Type/ArticleType.php
<?php

namespace AppBundle\Form\Type;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('description', TextareaType::class, [
                'attr' => ['rows' => 5]
            ])
            ->add('category', EntityType::class, [
                'class' => 'AppBundle:ArticleCategory',
                'choice_label' => 'label',
            ]);
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Article'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_article';
    }
}

src/AppBundle/Controller/ArticleController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\ArticleVote;
use AppBundle\Form\Type\ArticleType;
use AppBundle\Entity\Article;
use AppBundle\Form\Type\ArticleVoteType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


class ArticleController extends Controller
{
    /**
     * @Route("/articles", name="get_articles")
     * @Method({"GET"})
     * @return Response
     */
    public function getArticlesAction(): Response
    {
        $articles = $this->getDoctrine()->getRepository('AppBundle:Article')
            ->findAll();

        return $this->render('AppBundle:Article:get_articles.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/articles/add", name="post_articles")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @return Response
     */
    public function postArticlesAction(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $status = $em->getRepository('AppBundle:ArticleStatus')
                ->find(1);
            $article->setUser($this->getUser());
            $article->setStatus($status);
            $em->persist($article);
            $em->flush();

            $this->sendMailNewArticle($article);

            return $this->redirectToRoute('get_articles');
        }

        return $this->render('AppBundle:Article:post_articles.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/articles/{id}", name="get_article")
     * @Method({"GET", "POST"})
     * @param int $id
     * @return Response
     */
    public function getArticleAction(int $id): Response
    {
        $article = $this->getDoctrine()->getRepository('AppBundle:Article')
            ->find($id);

        if (!$article) {
            $this->articleNotFound();
        }

        $myVote = $this->getDoctrine()->getRepository('AppBundle:ArticleVote')
            ->findOneBy([
                'article' => $article,
                'user' => $this->getUser()
            ]);

        return $this->render('AppBundle:Article:get_article.html.twig', [
            'article' => $article,
            'myVote' => $myVote
        ]);
    }

    /**
     * @Route("/articles/{id}/votes/add", name="post_article_votes")
     * @Method({"GET", "POST"})
     * @param Int $id
     * @param Request $request
     * @return Response
     */
    public function postArticleVotesAction(int $id, Request $request): Response
    {
        $article = $this->getDoctrine()->getRepository('AppBundle:Article')
            ->find($id);

        if (!$article) {
            $this->articleNotFound();
        }

        $myVote = $this->getDoctrine()->getRepository('AppBundle:ArticleVote')
            ->findOneBy([
                'article' => $article,
                'user' => $this->getUser()
            ]);

        if ($article->getStatus()->getId() == 1) {
            $articleVote = new ArticleVote();
            $articleVote->setArticle($article);
            $articleVote->setUser($this->getUser());
            $form = $this->createForm(ArticleVoteType::class, $articleVote, [
                'action' => $this->generateUrl('post_article_votes', [
                    'id' => $article->getId()
                ])
            ]);

            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $this->get('role_service')->adminOrException();
                $em = $this->getDoctrine()->getManager();
                $em->persist($articleVote);
                $em->flush();

                $this->sendMailVoteArticle($articleVote);

                return $this->redirectToRoute('get_article', [
                    'id' => $article->getId()
                ]);
            }
        }

        $params = [
            'article' => $article,
            'myVote' => $myVote
        ];
        if (isset($form)) {
            $params['form'] = $form->createView();
        }

        return $this->render('AppBundle:Article/Partial:post_article_votes.html.twig', $params);
    }

    /**
     * @Route("/articles/{id}/status", name="patch_article_status")
     * @Method({"GET", "POST"})
     * @param Int $id
     * @param Request $request
     * @return Response
     */
    public function patchArticleStatusAction(int $id, Request $request): Response
    {
        $article = $this->getDoctrine()->getRepository('AppBundle:Article')
            ->find($id);

        if (!$article) {
            $this->articleNotFound();
        }

        $myVote = $this->getDoctrine()->getRepository('AppBundle:ArticleVote')
            ->findOneBy([
                'article' => $article,
                'user' => $this->getUser()
            ]);

        if ($article->getStatus()->getId() == 1) {
            if ($request->isMethod('POST')) {
                $this->get('role_service')->adminOrException();

                $status = $this->getDoctrine()->getRepository('AppBundle:ArticleStatus')
                    ->find($request->request->get('status_id'));

                if (!$status) {
                    $this->statusNotFound();
                }

                if ($status->getId() == 2) {
                    $article->setLink($request->request->get('link'));
                }

                $article->setStatus($status);
                $em = $this->getDoctrine()->getManager();
                $em->merge($article);
                $em->flush();

                $this->sendMailStatusArticle($article);

                return $this->redirectToRoute('get_article', [
                    'id' => $article->getId()
                ]);
            }
        }

        return $this->render('AppBundle:Article/Partial:patch_article_status.html.twig', [
            'article' => $article,
            'myVote' => $myVote
        ]);
    }

    private function sendMailNewArticle(Article $article)
    {
        $users = $this->getDoctrine()->getRepository('AppBundle:User')
            ->findModerators();

        foreach ($users as $user) {
            $message = (new \Swift_Message())
                ->setSubject($this->get('translator')->trans('email.new-article.title'))
                ->setFrom('no-reply@darkmira.com', 'Darkmira')
                ->setTo($user->getEmail())
                ->setBody(
                    $this->get('templating')->render('@App/Email/new_article.html.twig', [
                        'article' => $article
                    ]),
                    'text/html'
                );
            $this->get('mailer')->send($message);
        }
    }

    private function sendMailVoteArticle(ArticleVote $vote)
    {
        $users = $this->getDoctrine()->getRepository('AppBundle:User')
            ->findModerators();

        foreach ($users as $user) {
            $message = (new \Swift_Message())
                ->setSubject($this->get('translator')->trans('email.vote-article.title'))
                ->setFrom('no-reply@darkmira.com', 'Darkmira')
                ->setTo($user->getEmail())
                ->setBody(
                    $this->get('templating')->render('@App/Email/vote_article.html.twig', [
                        'article' => $vote->getArticle(),
                        'vote' => $vote
                    ]),
                    'text/html'
                );
            $this->get('mailer')->send($message);
        }
    }

    private function sendMailStatusArticle(Article $article)
    {
        $users = $this->getDoctrine()->getRepository('AppBundle:User')
            ->findModerators();
        $users[] = $this->getUser();

        foreach ($users as $user) {
            $message = (new \Swift_Message())
                ->setSubject($this->get('translator')->trans('email.status-article.title'))
                ->setFrom('no-reply@darkmira.com', 'Darkmira')
                ->setTo($user->getEmail())
                ->setBody(
                    $this->get('templating')->render('@App/Email/status_article.html.twig', [
                        'article' => $article
                    ]),
                    'text/html'
                );
            $this->get('mailer')->send($message);
        }
    }

    /**
     * @return NotFoundHttpException
     */
    private function articleNotFound(): NotFoundHttpException
    {
        throw new NotFoundHttpException('Article not found.');
    }

    /**
     * @return NotFoundHttpException
     */
    private function statusNotFound(): NotFoundHttpException
    {
        throw new NotFoundHttpException('Status not found.');
    }
}

src/AppBundle/Resources/views/Article/Partial/patch_article_status.html.twig
{% if is_granted('ROLE_ADMIN') and myVote %}
<form action="{{ path('patch_article_status', {id: article.id}) }}" method="post" name="app_article_status">
    <input type="hidden" id="app_article_status" name="status_id"/>
    <input type="hidden" id="app_article_link" name="link"/>
    {% endif %}
    {% if myVote %}
        <p class="m-t-lg text-center">
            {% if article.status.id == 1 %}
                {% if is_granted('ROLE_ADMIN') %}
                    <button id="article_status_accept" class="btn btn-w-m btn-primary m-r-sm"
                            {% if not myVote %}disabled{% endif %}>{{ 'article.form.action.accept'|trans }}</button>
                    <button id="article_status_refuse" class="btn btn-w-m btn-danger m-l-sm"
                            {% if not myVote %}disabled{% endif %}>{{ 'article.form.action.refuse'|trans }}</button>
                {% else %}
                    <span class="label label-warning">{{ 'article.status.pending'|trans }}</span>
                {% endif %}
            {% elseif article.status.id == 2 %}
                <a class="btn btn-info" target="_blank"
                   href="{{ article.link }}">{{ 'article.action.edit-document'|trans }}</a>
            {% else %}
                <span class="label label-default">{{ 'article.status.refused'|trans }}</span>
            {% endif %}
        </p>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') and myVote %}
</form>
{% endif %}

{% if is_granted('ROLE_ADMIN') and myVote %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $('[name="app_article_status"] #article_status_accept').click(function (e) {
                e.preventDefault();

                var $form = $(this).closest('form');
                var $status = $form.find('#app_article_status');
                var $link = $form.find('#app_article_link');

                swal({
                    title: "{{ 'article.status.accept.title'|trans }}",
                    text: "{{ 'article.status.accept.msg'|trans }}",
                    type: "input",
                    showCancelButton: true,
                    cancelButtonText: "{{ 'article.status.action.cancel'|trans }}",
                    closeOnConfirm: false,
                    confirmButtonText: "{{ 'article.form.action.accept'|trans }}",
                    inputPlaceholder: "{{ 'entity.article.link.placeholder'|trans }}"
                }, function (link) {
                    if (link === false) {
                        return false;
                    }

                    if (link === "") {
                        swal.showInputError("You need to write something!");
                        return false;
                    }

                    $link.val(link);
                    $status.val(2);
                    $form.submit();
                });

            });
            $('[name="app_article_status"] #article_status_refuse').click(function (e) {
                e.preventDefault();

                var $form = $(this).closest('form');
                var $status = $form.find('#app_article_status');

                swal({
                    title: "{{ 'article.status.refuse.title'|trans }}",
                    text: "{{ 'article.status.refuse.msg'|trans }}",
                    type: "warning",
                    showCancelButton: true,
                    cancelButtonText: "{{ 'article.status.action.cancel'|trans }}",
                    confirmButtonText: "{{ 'article.form.action.refuse'|trans }}",
                    closeOnConfirm: false
                }, function () {
                    $status.val(3);
                    $form.submit();
                });
            });
        });
    </script>
{% endif %}

src/AppBundle/Resources/views/Article/Partial/post_article_votes.html.twig
<div class="row m-t-lg text-center">
    {% if form is defined and is_granted('ROLE_ADMIN') %}
        {{ form_start(form) }}
    {% endif %}
    <div class="col-xs-6">
        <h1 class="text-right">
            {% if is_granted('ROLE_ADMIN') %}
                {% if myVote %}
                    <span class="m-r-md {% if myVote.accepted %}text-info{% else %}text-muted{% endif %}"
                          data-toggle="tooltip" data-placement="left"
                          title="{% for vote in article.acceptedVotes %}{{ vote.user.email }} {% endfor %}">
                        <span>{{ article.acceptedVotes|length }}</span>
                        <i class="fa fa-thumbs-up"></i>
                    </span>
                {% else %}
                    <a id="article_vote_accept" class="m-r-md">
                        <span>{{ article.acceptedVotes|length }}</span>
                        <i class="fa fa-thumbs-up"></i>
                    </a>
                {% endif %}
            {% else %}
                <span class="m-l-md {% if article.acceptedVotes|length >= article.refusedVotes|length and article.acceptedVotes|length > 0 %}text-info{% endif %}">
                    <span>{{ article.acceptedVotes|length }}</span>
                    <i class="fa fa-thumbs-up"></i>
                </span>
            {% endif %}
        </h1>
    </div>
    <div class="col-xs-6">
        <h1 class="text-left">
            {% if is_granted('ROLE_ADMIN') %}
                {% if myVote %}
                    <span class="m-l-md {% if not myVote.accepted %}text-danger{% else %}text-muted{% endif %}"
                          data-toggle="tooltip" data-placement="right"
                          title="{% for vote in article.refusedVotes %}{{ vote.user.email }} {% endfor %}">
                        <span>{{ article.refusedVotes|length }}</span>
                        <i class="fa fa-thumbs-down"></i>
                    </span>
                {% else %}
                    <a id="article_vote_refuse" class="m-l-md">
                        <span>{{ article.refusedVotes|length }}</span>
                        <i class="fa fa-thumbs-down"></i>
                    </a>
                {% endif %}
            {% else %}
                <span class="m-l-md">
                    <span>{{ article.refusedVotes|length }}</span>
                    <i class="fa fa-thumbs-down"></i>
                </span>
            {% endif %}
        </h1>
    </div>
    {% if form is defined and is_granted('ROLE_ADMIN') %}
        {{ form_rest(form) }}
        {{ form_end(form) }}
    {% endif %}
</div>

{% if form is defined and is_granted('ROLE_ADMIN') %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $('[name="app_article_vote"] #article_vote_accept').click(function () {
                var $form = $(this).closest('form');
                var $input = $form.find('#app_article_vote_isAccepted');

                $input.val(1);
                $form.submit();
            });
            $('[name="app_article_vote"] #article_vote_refuse').click(function () {
                var $form = $(this).closest('form');
                var $input = $form.find('#app_article_vote_isAccepted');

                $input.val(0);
                $form.submit();
            });
        });
    </script>
{% endif %}

src/AppBundle/Resources/views/Article/Partial/post_votes.html.twig
<div class="row m-t-lg text-center">
    {% if form is defined %}
        {{ form_start(form) }}
    {% endif %}
    <div class="col-xs-6">
        <h1 class="text-right">
            {% if myVote %}
                <span class="m-r-md {% if myVote.accepted %}text-info{% else %}text-muted{% endif %}">
                    <span>{{ article.acceptedVotes|length }}</span>
                    <i class="fa fa-thumbs-up"></i>
                </span>
            {% else %}
                <a id="article_vote_accept" class="m-r-md">
                    <span>{{ article.acceptedVotes|length }}</span>
                    <i class="fa fa-thumbs-up"></i>
                </a>
            {% endif %}
        </h1>
    </div>
    <div class="col-xs-6">
        <h1 class="text-left">
            {% if myVote %}
                <span class="m-l-md {% if not myVote.accepted %}text-danger{% else %}text-muted{% endif %}">
                    <span>{{ article.refusedVotes|length }}</span>
                    <i class="fa fa-thumbs-down"></i>
                </span>
            {% else %}
                <a id="article_vote_refuse" class="m-l-md">
                    <span>{{ article.refusedVotes|length }}</span>
                    <i class="fa fa-thumbs-down"></i>
                </a>
            {% endif %}
        </h1>
    </div>
    {% if form is defined %}
        {{ form_rest(form) }}
        {{ form_end(form) }}
    {% endif %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        $form = $('[name="app_article_vote"]');
        $input = $form.find('#app_article_vote_isAccepted');

        $form.find('#article_vote_accept').click(function () {
            console.log('click');
            $input.val(1);
            $form.submit();
        });
        $form.find('#article_vote_refuse').click(function () {
            $input.val(0);
            $form.submit();
        });
    })
</script>